services:
  auth-app:
    build: .
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
